### ISSUE TITLE
Internal Buildpacks Error with new `heroku/procfile@3.0.0` version

### ISSUE THREAD

**Issue by HeavyWombat** [heroku/procfile-cnb#214]
Since yesterday, we observe the following error that breaks our builds:

```
step-build-and-push [Error: Internal Buildpack Error]
step-build-and-push Couldn't determine target os: environment variable not found
step-build-and-push err:  heroku/procfile@3.0.0 (1)
step-build-and-push ======== Output: heroku/procfile@3.0.0 ========
```

It looks like the new version does something different with regards to obtaining the operating system through an environment variable?

**Comment by edmorley** [comment]
@HeavyWombat Hi! 

The v3.0.0 release of Procfile CNB upgraded the buildpack from Buildpack API 0.8 to 0.10, mentioned in the changelog here:
https://github.com/heroku/procfile-cnb/blob/main/CHANGELOG.md#300---2024-02-28

In Buildpack API 0.10, the spec states that when the buildpack is run, various `CNB_TARGET_*` env vars are set:
https://github.com/buildpacks/spec/releases/tag/buildpack%2Fv0.10
https://github.com/buildpacks/rfcs/blob/main/text/0096-remove-stacks-mixins.md#runtime-metadata
https://github.com/buildpacks/spec/blob/main/buildpack.md#provided-by-the-lifecycle

If you're seeing that error message, it means that the env var `CNB_TARGET_OS` is not set, and we're failing to read it here:
https://github.com/heroku/libcnb.rs/blob/f0983996fd4e8a0cf5bb916ed4608b731fb6474c/libcnb/src/runtime.rs#L365
https://github.com/heroku/libcnb.rs/blob/f0983996fd4e8a0cf5bb916ed4608b731fb6474c/libcnb/src/error.rs#L26-L27

The error message could make this a little clearer - I've filed https://github.com/heroku/libcnb.rs/issues/803 to improve it. 

We didn't really expect anyone to see that error message, since it's a spec violation if the env var is not set.

What `lifecycle` version are you using?

Buildpack API 0.10 requires at least lifecycle `0.17` or newer:
https://github.com/buildpacks/lifecycle?tab=readme-ov-file#supported-apis

However, I would have thought older `lifecycle` versions would fail with a "Buildpack API 0.10 isn't supported" type error message, rather than trying to perform the build without the correct env vars set?

**Comment by edmorley** [comment]
Also, I'm pretty sure you shouldn't need to set those env vars manually (since that's something that `lifecycle` should be doing), so I'm not sure https://github.com/shipwright-io/build/pull/1511 is the correct fix?

However, I'm not completely familiar with invoking `lifecycle` manually (as I see happens in https://github.com/shipwright-io/build), so this might be something you need to ask about at:
https://github.com/buildpacks/lifecycle/issues

Or on their Slack:
https://buildpacks.io/community/

**Comment by HeavyWombat** [comment]
@edmorley Thanks for the detailed explanation, it now becomes more clear to me how we ended up with the error in the first place. To be honest, my [Shipwright PR](https://github.com/shipwright-io/build/pull/1511) was mostly done based on a gut feeling and a local test that showed that adding these environment variables made the test cases work again, since the [library changes](https://github.com/heroku/libcnb.rs/commit/033f6128c647b7bc6effc8b80fae8b96a4373169#diff-0fb7b6592b937533caedc8eeb5871247de5b2abae0b1fa7044e88bac0f25a593R365-R366) clearly pointed into this direction. I did browse over the release notes and change logs, but I obviously missed that note, so thanks for that pointer.

Due to the way that the build strategies work and the Kubernetes setup, I think we are using Buildpacks in a slightly different style than most users.

And thanks for https://github.com/heroku/libcnb.rs/issues/803, even though we are pretty much the definition of an edge case scenario here, I think it can help. Being unfamiliar with the code base, it took me a bit to dig down to the library to finally make sense of the error message in terms of what it wants to read.

I really appreciate your help here! I think we can close the issue.

**Comment by edmorley** [comment]
Happy to help! Glad you figured out a fix :-)

**Comment by edmorley** [comment]
> Also, I'm pretty sure you shouldn't need to set those env vars manually (since that's something that `lifecycle` should be doing), so I'm not sure [shipwright-io/build#1511](https://github.com/shipwright-io/build/pull/1511) is the correct fix?

Yeah this has been confirmed as a `lifecycle` bug when using Platform API versions < 0.12:
https://github.com/buildpacks/lifecycle/issues/1308
